# Streams

A **Stream** is a list of arbitrary length which can be modified only by appending values to the tail of the list. A **StreamArray** is a NumPy array of arbitrary length to which rows can be appended at the end.
<br>
The most recent elements of a stream are stored in main memory. Older elements can be stored in files. The amount that is stored in main memory can be specified or left as a default value. We discuss this later. For a Stream *x* the most recent values of *x* are in a list *recent_values(x)*. For a StreamArray *x*: *recent_values(x)* is an array.

## Creating a Stream

*s = Stream(name=‘temperature’, initial_value=[20, 21, 20])*

creates a stream with the specified name and initial value. Both the name and initial value can be omitted.
The default initial value is the empty stream.

## Example of creating a stream

In [1]:
import os
import sys
sys.path.append("../")

In [2]:
from IoTPy.core.stream import Stream, run
from IoTPy.helper_functions.recent_values import recent_values

In [3]:
def example():
    s = Stream(name='temperature', initial_value=[20, 21, 20])

## Appending an element to a Stream
You append an element to a Stream in the same way as for a list.
<br>
Example:
*s.append(22)* appends the value 22 to the tail of stream *s*.

In [4]:
def example():
    s = Stream(name='temperature', initial_value=[20, 21, 20])
    s.append(22)

## Extending a Stream with a list of elements
You can extend a stream in the same way that you extend a list. 
<br>
Example:

*s.extend([22, 21])* extends stream *s* with the elements of the list [22, 21] appended to its tail.

In [5]:
def example():
    s = Stream(name='temperature', initial_value=[20, 21, 20])
    s.extend([22, 21])

# Examples
While you are testing the system you call the function *run()* to execute a single step in processing the stream. We will discuss starting networks of streams later.

The next blocks show how to use *run()* to inspect the most recent values of a stream.

In [6]:
# Example of declaring a stream
def example():
    s = Stream(name='temperature', initial_value=[20, 21, 20])
    # run a step
    run()
    print (recent_values(s))

example()

[20, 21, 20]


In [7]:
# Example of appending an element to a stream
def example():
    s = Stream(name='temperature', initial_value=[20, 21, 20])
    s.append(22)

    # run a step
    run()
    print (recent_values(s))

example()

[20, 21, 20, 22]


In [8]:
# Example of extending a stream
def example():
    s = Stream(name='temperature', initial_value=[20, 21, 20])
    s.extend([22, 21])

    # run a step
    run()
    print (recent_values(s))

example()

[20, 21, 20, 22, 21]


# Standard operators on streams
You can use standard operators:

<br>
** +, -, *, /, //, <, <=, ==, !=, >, >= **

<br>
to merge streams to return a stream.

<br>
Example:
<br>
v = s + t - u
<br>
declares a stream *v* where *v[n] = s[n] + t[n] - u[n]* for all *n*.


In [9]:
# Example of operators on a stream
def example():
    s = Stream()
    t = Stream()
    u = Stream()
    # Declare the composed stream
    v = s + t - u
    
    s.extend([22, 21])
    t.extend([10, 20, 30])
    u.extend([1, 2, 3, 4])
    # run a step
    run()
    
    print ("s is: ", recent_values(s))
    print ("t is: ", recent_values(t))
    print ("u is: ", recent_values(u))
    print ("v is: ", recent_values(v))

example()

s is:  [22, 21]
t is:  [10, 20, 30]
u is:  [1, 2, 3, 4]
v is:  [31, 39]


# StreamArray
The statement:

*s = StreamArray(name='s', dimension=3, dtype=int)*

creates a stream *s* where *s[n]* is a NumPy array consisting of an unbounded number of rows and 3 (i.e. dimension) columns and where the elements of the array are of type *int*. An item appended to this stream must be an array consisting of 3 integers; appending such a 3-element array appends a single row containing the 3 integers to the tail of s.

The parameters of **StreamArray** are: **name, dimension, dtype, initial_value,** and **num_in_memory**

1. **name** is optional and is a string. The default is ‘no_name’.

2. **dimension** is optional and is the dimension of elements of the stream array. The default is 0.

3. **dtype** is optional and the type of the rows of the stream array. The default is float.

4. **initial_value** is optional and is the initial value of the stream array. The default is None.

1. **num_in_memory** is optional and can be ignored for the time being. It is used for memory management.

## StreamArray with dimension = 0

The **dimension** parameter can be a non-negative integer or a tuple or list. If dimension is 0 then each element of the stream array belongs to type dtype. In this case, think of the stream array as a 1-D array of unbounded length with elements of type dtype. 

For example:

*t = StreamArray()*

makes *t* a stream array where *t* is effectively an array of unbounded size where each element of *t* is a float.

## StreamArray where dimension is a positive integer

If **dimension** is a positive integer then each element of the stream is a 1-D array whose length is **dimension**. For example:

*u = StreamArray(name='pressure', dimension=2, dtype=float)*

makes *u* a stream array called pressure. Think of *u* as an array with an unbounded number of rows where each row of *u* is an array consisting of 2 floats.


## StreamArray where dimension is a tuple or list

**dimension** can be a tuple or list. Each element of the tuple must be a positive integer. Think of the stream array as having an unbounded number of rows where each row is an N-dimensional array where N is the length of the tuple. The lengths of the N-dimensional array are given by the tuple. For example, 

*v = StreamArray(dimension=(3,4), dtype=int)*

makes *v* a stream array where each row of *v* is a 3 x 4 array of integers.

## Appending an element to a StreamArray

Next, let's look at examples of appending an element to a stream array for the cases where the **dimension** parameter is 0, a positive integer, and a tuple.

## Example of StreamArray with default dimension of 0

In [10]:
import numpy as np
from IoTPy.core.stream import StreamArray

def example():
    t = StreamArray()
    t.append(np.array(1.0))
    
    # run a step and print
    run()
    print ("t is :", recent_values(t))
    
    t.append(np.array(2.0))
    
    # run a step and print
    run()
    print ("t is :", recent_values(t))


example()

t is : [1.]
t is : [1. 2.]


## Example of StreamArray of int when dimension is a positive integer
### StreamArray of int

In [11]:
def example():
    s = StreamArray(name='temperatures', dimension=3, dtype=int)
    
    s.append(np.zeros(3, dtype=int))
    
    # run a step and print
    run()
    print ("s is :")
    print (recent_values(s))
    
    s.append(np.array([1, 2, 3]))
    
    # run a step and print
    run()
    print ("s is :")
    print (recent_values(s))

example()

s is :
[[0 0 0]]
s is :
[[0 0 0]
 [1 2 3]]


## Example of StreamArray of float when dimension is a positive integer
### StreamArray of float

In [12]:
def example():
    u = StreamArray(name='pressure', dimension=3, dtype=float)
    
    u.append(np.array([0.0, 0.0, 0.0]))
    
    # run a step and print
    run()
    print ("u is :")
    print (recent_values(u))
    
    u.append(np.array([1.0, 2.0, 3.0]))
    
    # run a step and print
    run()
    print ("u is :")
    print (recent_values(u))

example()

u is :
[[0. 0. 0.]]
u is :
[[0. 0. 0.]
 [1. 2. 3.]]


## Example of StreamArray when dimension is a tuple

In [13]:
def example():
    v = StreamArray(name="prices", dimension=(3,4), dtype=int)
    # Each element of v is a numpy array with 3 rows and 4 columns
    
    v.append(np.array([
        [0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]]))
    
    # run a step and print
    run()
    print ("v is :")
    print (recent_values(v))
    
    v.append(np.array([
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))
    
    # run a step and print
    run()
    print ("v is :")
    print (recent_values(v))

example()

v is :
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
v is :
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


# Extending StreamArray


## Example: Extend StreamArray of float with dimension of 0
### Extend the StreamArray with a linear numpy array of the same type

In [14]:
def example():
    # default dtype is float and default dimension is 0
    t = StreamArray()
    t.extend(np.array([1.0, 2.0]))
    
    # run a step and print
    run()
    print ("t is :", recent_values(t))
    
    t.extend(np.array([3.0, 4.0]))
    
    # run a step and print
    run()
    print ("t is :", recent_values(t))


example()

t is : [1. 2.]
t is : [1. 2. 3. 4.]


## Example: Extend StreamArray when dimension is a positive integer
### StreamArray of int

You can extend a **StreamArray** by an array consisting of multiple rows where the dimensions of rows of the array and the **StreamArray** are identical.

In [19]:
def example():
    s = StreamArray(name='temperatures', dimension=3, dtype=int)
    # Extend s with a numpy array with an arbitrary (positive) number
    # of rows and 3 columns
    
    s.extend(np.array(
        [[0, 1, 2],
        [3, 4, 5]]
    ))
    
    # run a step and print
    run()
    print ("s is :")
    print (recent_values(s))
    
    s.extend(np.array(
        [[6, 7, 8],
        [9, 10, 11],
        [12, 13, 14]]
    ))
    
    # run a step and print
    run()
    print ("s is :")
    print (recent_values(s))
             
example()



s is :
[[0 1 2]
 [3 4 5]]
s is :
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Example: Extend StreamArray where dimension is a tuple

Extend the StreamArray with a numpy array with an arbitrary (positive) number of rows and where each row is a numpy array with the specified dimensions.

In [20]:
def example():
    v = StreamArray(name="prices", dimension=(3,4), dtype=int)
    # Extend v with a numpy array with an arbitrary positive number
    # of rows and where each row is an array with dimension (3, 4)
    
    # Example: extend v with a numpy array with 2 rows, and where
    # each row is a numpy array with dimension (3, 4)
    v.extend(np.array([
        [[12, 13, 14, 15],[16, 17, 18, 19], [20, 21, 22, 23]],
        [[24, 25, 26, 27], [28, 29, 30, 31], [32, 33, 34, 35]]]))
    
    # run a step and print
    run()
    print ("v is :")
    print (recent_values(v))
    
    # Example: append v with a numpy array with dimension (3, 4)
    v.append(np.array([
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))
    
    # run a step and print
    run()
    print ("v is :")
    print (recent_values(v))

example()

v is :
[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
v is :
[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


# StreamArray with user-defined types


An example of a user-defined type is:

*txyz_dtype = np.dtype([('time','int'), ('data', '3float')])*

An example of an object, *c*, of this type is created by:

*c = np.array((1, [0.0, 1.0, 2.0]), dtype=txyz_dtype)*

Then, *c[‘time’]* has type *np.array(1)*, and *c['data']* has type *np.array([ 0.0,  1.0,  2.0]*

## Creating a StreamArray with user-defined types

*y = StreamArray(dimension=0, dtype=txyz_dtype)*

creates a stream array, *y*, whose elements are of type *txyz_dtype*. Think of *y* as an array with an arbitrary number of rows where each row is an array of type *txyz_dtype*.

### Examples of appending and extending a StreamArray with user-defined types

In [17]:
def example():
    
    txyz_dtype = np.dtype([('time','int'), ('data', '3float')])
    
    y = StreamArray(dimension=0, dtype=txyz_dtype)
    
    y.append(
        np.array((1, [0.0, 1.0, 2.0]), dtype=txyz_dtype)
    )
    
    # run a step and print
    run()
    print ("y is :")
    print (recent_values(y))
    
    y.extend(
        np.array([
            (2, [3., 4., 5.]), 
            (3, [6., 7., 8.])], 
            dtype=txyz_dtype)
    )
    
    # run a step and print
    run()
    print ("y is :")
    print (recent_values(y))

example()

y is :
[(1, [0., 1., 2.])]
y is :
[(1, [0., 1., 2.]) (2, [3., 4., 5.]) (3, [6., 7., 8.])]


## Example: Operators on StreamArrays

Operations such as + and * can be carried out on **StreamArrays** of the same dimensions.

In [18]:
def example():
    t = StreamArray()
    u = StreamArray()
    v = t*u
    
    t.extend(np.array([1.0, 2.0]))
    u.extend(np.array([10.0, 20.0]))
    
    
    # run a step and print
    run()
    print ("t is :", recent_values(t))
    print ("u is :", recent_values(u))
    print ("v is :", recent_values(v))
    
    
    t.extend(np.array([3.0, 4.0]))
    u.extend(np.array([30.0, 40.0]))
    
    # run a step and print
    run()
    print ("t is :", recent_values(t))
    print ("u is :", recent_values(u))
    print ("v is :", recent_values(v))


example()

t is : [1. 2.]
u is : [10. 20.]
v is : [10. 40.]
t is : [1. 2. 3. 4.]
u is : [10. 20. 30. 40.]
v is : [ 10.  40.  90. 160.]
